version: "3"
services:
 mongodb:
   #image: nginx
   image: mongo
   ports: 
    - 27017:27017
   environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=pass
   
  
 mongo-express:
   #image: httpd
   image: mongo-express
   ports:
    - 8080:8081
   environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=root
   - ME_CONFIG_MONGODB_ADMINUSERPASSWORD=pass
   - ME_CONFIG_MONGODB_SERVER=mongo
